### ISSUE TITLE
Remove side-effects

### ISSUE THREAD

**Issue by austinpray** [roots/bedrock-autoloader#6]
Autoloading the Autloader class should not cause side-effects

- [x] https://github.com/roots/bedrock-autoloader/blob/02e61a6f7ff78c2d77599843617f88156c4c6274/src/Autoloader.php#L14-L16
- [x] https://github.com/roots/bedrock-autoloader/blob/02e61a6f7ff78c2d77599843617f88156c4c6274/src/Autoloader.php#L14-L16

**Comment by austinpray** [comment]
closed by https://github.com/roots/bedrock-autoloader/pull/16

Thank you @aaemnnosttv!

**Comment by aaemnnosttv** [comment]
Didn't realize this was already an issue! 😄
